# Generated by Django 3.2.13 on 2023-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('visitorID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Visitante #')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo Electronico')),
                ('coments', models.TextField(max_length=200, verbose_name='Comentarios')),
            ],
        ),
    ]
