# Generated by Django 3.2.13 on 2023-01-31 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('iduser', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicacion')),
                ('type', models.CharField(choices=[('FOTOGRAFO', 'FT'), ('CLIENTE', 'CL')], default='', max_length=10, verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
