# Generated by Django 3.2.13 on 2023-01-31 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='imagegallery',
            fields=[
                ('imageID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID #')),
                ('imagename', models.CharField(max_length=20, verbose_name='Titulo de Foto')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Fotografia')),
                ('imagedescription', models.TextField(verbose_name='descripcion')),
                ('categoryimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageapp.category')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profile')),
            ],
        ),
    ]
