# Generated by Django 3.2.13 on 2023-01-31 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='categoryimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageapp.category', verbose_name='categoria'),
        ),
    ]
